{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "bdapp.fullname" . }}
  namespace: {{ default "default" .Values.namespace }}
  labels:
    {{- include "bdapp.labels" . | nindent 4 }}
  {{- with .Values.virtualService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    {{- toYaml .Values.virtualService.hosts | nindent 4 }}
  gateways:
    {{- toYaml .Values.virtualService.gateways | nindent 4 }}
  http:
  {{- range .Values.virtualService.paths }}
  - {{- with .match }}
    match:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    route:
    - destination:
        host: {{ include "bdapp.destination-host" (list $ .) }}
        port:
          number: {{ .port.number }}
    {{- with .rewrite }}
    rewrite:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .cors }}
    corsPolicy:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end -}}