{{- if (.Values.clusterController).enabled }}
{{- if and .Values.clusterController.createClusterControllerSecret .Values.clusterController.kubecostAPIKey }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.clusterController.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
data:
  kubecostAPIKey: {{ .Values.clusterController.kubecostAPIKey | b64enc }}
{{- end }}
{{- end }}