{{- if (.Values.clusterController).enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubecost.clusterController.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "kubecost.commonLabels" . | nindent 4 }}
{{- end }}