{{- if eq (include "kubecost.rbacTeams.enabled" .) "true" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kubecost-rbac-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
stringData:
  key:
    {{- if .Values.oidc.enabled }}
    {{ .Values.oidc.authSecret | default (randAlphaNum 32 | quote) }}
    {{- end }}
    {{- if .Values.saml.enabled }}
    {{ .Values.saml.authSecret | default (randAlphaNum 32 | quote) }}
    {{- end }}
{{- end }}
