{{- if .Values.kubecostProductConfigs }}
{{- if .Values.kubecostProductConfigs.productKey }}
{{- if .Values.kubecostProductConfigs.productKey.enabled }}
# If the productKey.key is not specified, the configmap will not be created
{{- if .Values.kubecostProductConfigs.productKey.key }}
# If the secretname is specified, the configmap will not be created
{{- if not .Values.kubecostProductConfigs.productKey.secretname }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubecost.productKey.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
data:
    productkey.json: {{ ( printf "{\"key\": \"%s\"}" .Values.kubecostProductConfigs.productKey.key ) | b64enc }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}