apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kubecost.serviceAccountName" . }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kubecost.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kubecost.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
