{{- if (.Values.networkCosts).enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubecost.networkCosts.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "kubecost.commonLabels" . | nindent 4 }}
{{- end }}